services:
  mysql:
    image: mysql:8.0
    container_name: netherlink-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "netherlink"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./netherlink.sql:/docker-entrypoint-initdb.d/init.sql
